// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eagjutdyxkttctsssbmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZ2p1dGR5eGt0dGN0c3NzYm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTk1OTEsImV4cCI6MjA3MzU3NTU5MX0.ILsJSxeN9eGZ1dvoanRH3FLrLctELyGQWUl0L5TNlyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});